@startuml

left to right direction


class BaseOceanStateEnsemble
class EnsembleFromFile
class OceanNoiseEnsemble
class DoubleJetExperiment



BaseOceanStateEnsemble : [Simulator] particles
BaseOceanStateEnsemble : nx, ny, dx, dy
BaseOceanStateEnsemble : numParticles

BaseOceanStateEnsemble : step()
BaseOceanStateEnsemble : observeParticles()
BaseOceanStateEnsemble : getInnovations()
BaseOceanStateEnsemble : getObservationCov()

BaseOceanStateEnsemble --> EnsembleFromFile

EnsembleFromFile : [Observation] observations

EnsembleFromFile : _initializeTruthFromFile()
EnsembleFromFile : _initializeEnsembleFromFile()
EnsembleFromFile : observeTrueState()

EnsembleFromFile -> Observation

Observation : [pd.DataFrame] obs_df

Observation : add_observation_from_sim()
Observation : get_observation()

BaseOceanStateEnsemble --> OceanNoiseEnsemble

OceanNoiseEnsemble : observeTrueState()

OceanNoiseEnsemble --> DoubleJetExperiment



class Simulator
class CDKLM16

class OceanNoiseState

Simulator --> CDKLM16

Simulator : nx, ny, dx, dy
Simulator : [DataAssimilationUtils.Observation] drifters

Simulator : download()
Simulator : upload()

CDKLM16 : [OceanNoiseState] small_scale_model_error

CDKLM16 : step()
CDKLM16 : dataAssimilationStep()

CDKLM16 -> OceanNoiseState

OceanNoiseState : perturbSim()

@enduml